import type { AgentCV } from './types';

export function formatMarkdown(cv: AgentCV): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Agent CV`);
  lines.push('');
  lines.push(`**Address:** \`${cv.agent.address}\``);
  lines.push(`**Member Since:** ${new Date(cv.agent.memberSince).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(`**Reputation Score:** ${cv.agent.reputationScore > 0 ? `${cv.agent.reputationScore}/100` : 'Not rated yet'}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(cv.summary);
  lines.push('');

  // Skills
  if (cv.skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    const skillsList = cv.skills.map(s => `**${s.name}** (${s.frequency})`).join(' • ');
    lines.push(skillsList);
    lines.push('');
  }

  // Selected Work
  if (cv.selectedWork.length > 0) {
    lines.push('## Selected Work');
    lines.push('');
    for (const work of cv.selectedWork) {
      const rating = work.rating ? ` ⭐ ${work.rating}/100` : '';
      lines.push(`### $${work.reward.toFixed(2)} USDC${rating}`);
      lines.push('');
      lines.push(work.description);
      if (work.tags.length > 0) {
        lines.push('');
        lines.push(`*Tags: ${work.tags.join(', ')}*`);
      }
      lines.push('');
    }
  }

  // Stats Table
  lines.push('## Statistics');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Completed Tasks | ${cv.stats.completedTasks} |`);
  lines.push(`| Success Rate | ${cv.stats.successRate.toFixed(0)}% |`);
  lines.push(`| Total Earned | $${cv.stats.totalEarned.toFixed(2)} USDC |`);
  lines.push(`| Average Rating | ${cv.stats.averageRating > 0 ? cv.stats.averageRating.toFixed(0) + '/100' : 'N/A'} |`);
  lines.push(`| Average Reward | $${cv.stats.averageReward.toFixed(2)} USDC |`);
  lines.push('');

  // Footer
  lines.push('---');
  lines.push(`*Generated by AgentCV on ${new Date(cv.generatedAt).toISOString()}*`);

  return lines.join('\n');
}

export function formatHTML(cv: AgentCV): string {
  const md = formatMarkdown(cv);
  
  // Simple markdown to HTML conversion for PDF
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Agent CV - ${cv.agent.address}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #1a1a1a;
      background: #fff;
    }
    h1 { 
      font-size: 2.5rem; 
      margin-bottom: 1rem;
      color: #0f172a;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 0.5rem;
    }
    h2 { 
      font-size: 1.5rem; 
      margin: 2rem 0 1rem;
      color: #1e40af;
    }
    h3 { 
      font-size: 1.1rem; 
      margin: 1.5rem 0 0.5rem;
      color: #059669;
    }
    p { margin-bottom: 1rem; }
    code {
      background: #f1f5f9;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Monaco', 'Menlo', monospace;
      font-size: 0.9em;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #e2e8f0;
    }
    th { 
      background: #f8fafc;
      font-weight: 600;
      color: #475569;
    }
    .skills {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      margin: 1rem 0;
    }
    .skill {
      background: #dbeafe;
      color: #1e40af;
      padding: 4px 12px;
      border-radius: 16px;
      font-size: 0.9rem;
    }
    .meta {
      color: #64748b;
      font-size: 0.95rem;
      margin-bottom: 0.5rem;
    }
    hr {
      border: none;
      border-top: 1px solid #e2e8f0;
      margin: 2rem 0 1rem;
    }
    .footer {
      color: #94a3b8;
      font-size: 0.85rem;
      font-style: italic;
    }
    .work-item {
      background: #f8fafc;
      padding: 1rem;
      border-radius: 8px;
      margin-bottom: 1rem;
      border-left: 4px solid #3b82f6;
    }
    .tags {
      color: #64748b;
      font-size: 0.85rem;
      margin-top: 0.5rem;
    }
  </style>
</head>
<body>
  <h1>🤖 Agent CV</h1>
  
  <p class="meta"><strong>Address:</strong> <code>${cv.agent.address}</code></p>
  <p class="meta"><strong>Member Since:</strong> ${new Date(cv.agent.memberSince).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  <p class="meta"><strong>Reputation Score:</strong> ${cv.agent.reputationScore > 0 ? `${cv.agent.reputationScore}/100` : 'Not rated yet'}</p>

  <h2>📝 Summary</h2>
  <p>${cv.summary}</p>

  ${cv.skills.length > 0 ? `
  <h2>🛠️ Skills</h2>
  <div class="skills">
    ${cv.skills.map(s => `<span class="skill">${s.name} (${s.frequency})</span>`).join('')}
  </div>
  ` : ''}

  ${cv.selectedWork.length > 0 ? `
  <h2>💼 Selected Work</h2>
  ${cv.selectedWork.map(work => `
  <div class="work-item">
    <h3>$${work.reward.toFixed(2)} USDC ${work.rating ? `⭐ ${work.rating}/100` : ''}</h3>
    <p>${work.description}</p>
    ${work.tags.length > 0 ? `<p class="tags">Tags: ${work.tags.join(', ')}</p>` : ''}
  </div>
  `).join('')}
  ` : ''}

  <h2>📊 Statistics</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Completed Tasks</td><td>${cv.stats.completedTasks}</td></tr>
    <tr><td>Success Rate</td><td>${cv.stats.successRate.toFixed(0)}%</td></tr>
    <tr><td>Total Earned</td><td>$${cv.stats.totalEarned.toFixed(2)} USDC</td></tr>
    <tr><td>Average Rating</td><td>${cv.stats.averageRating > 0 ? cv.stats.averageRating.toFixed(0) + '/100' : 'N/A'}</td></tr>
    <tr><td>Average Reward</td><td>$${cv.stats.averageReward.toFixed(2)} USDC</td></tr>
  </table>

  <hr>
  <p class="footer">Generated by AgentCV on ${new Date(cv.generatedAt).toISOString()}</p>
</body>
</html>
`;
}
